name       : farstream
version    : 0.2.8
release    : 5
source     :
    - http://freedesktop.org/software/farstream/releases/farstream/farstream-0.2.8.tar.gz : 2b3b9c6b4f64ace8c83e03d1da5c5a2884c1cae10b35471072b574201ab38908
license    : LGPL-2.1
component  : desktop.library
summary    : Farstream - Audio/Video Communications Framework
description: |
    The Farstream (formerly Farsight) project is an effort to create a framework to deal with all known audio/video conferencing protocols. On one side it offers a generic API that makes it possible to write plugins for different streaming protocols, on the other side it offers an API for clients to use those plugins.
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(nice)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
